# Math definitions


__Disclaimer:__ Most of these definitions have been taken from wikipedia. I don't know how to cite in jupyter yet. 
***
**1. Manifold:**  
A manifold is a topological space, which is locally Euclidean. For example, earth is actually a sphere, but it looks flat at every point. All possible positions of a robotic arm could also be described with a manifold.  
***
**2. Bilinear Map:**  
Bilinear map is a function that combines elements of two vector spaces into an element of a third vector space and is linear in each of it's arguments. If B is some operation that has these linear properties:  
1. B(x + y, z) = B(x, z) + B(y, z)  
2. B(x, y + z) = B(x, y) + B(x, z)  
3. B(cx, y) = cB(x, y)  
Then, B would be a bilinear map. The multiplication operation could be an example of a bilinear map.
***
**3.Matrix Exponential:**  
It's defined as $$e^X = \sum_{k=0}^ {\infty}\frac{1}{k!}X^k$$
The $X^0$ is the identity matrix. 

For example: if $A = \begin{bmatrix} 3 & 7 \\ 2 & 5 \end{bmatrix}$, then 
$$
e^A = 1 \begin{bmatrix} 3 & 7 \\ 2 & 5 \end{bmatrix}^{0} + 1 \begin{bmatrix} 3 & 7 \\ 2 & 5 \end{bmatrix}^{1} + \frac{1}{2} \begin{bmatrix} 3 & 7 \\ 2 & 5 \end{bmatrix}^{2} + \frac{1}{6} \begin{bmatrix} 3 & 7 \\ 2 & 5 \end{bmatrix}^{3} + .....
$$
Let's see what the value becomes:
***




In [25]:
import math
import numpy as np
A = numpy.matrix([[3.0, 7.0], [2.0, 5.0]])
S = numpy.matrix([[0.0, 0.0], [0.0, 0.0]])
print('A is: \n', A)
for i in range(0, 30):
    S += (1 / math.factorial(i)) * np.linalg.matrix_power(A, i) 
print('exp(A) is: \n', S)    
    

A is: 
 [[3. 7.]
 [2. 5.]]
exp(A) is: 
 [[ 974.47155635 2371.52535254]
 [ 677.57867215 1652.0502285 ]]


***
**4.Matrix Logarithm:**    
It's the reverse operation of the matrix exponentiation. Defined as: 
$$log(B) = \sum_{k=1}^{\infty}(-1)^{k+1}\frac{(B-I)^k}{k}$$
Wiki says that we can calculate the log in this way if $\|B - I \| < 1$. Now, if a density matrix is: 
$$
M = \begin{bmatrix} \frac{3}{8} & \frac{3}{8} \\ \frac{3}{8} & \frac{5}{8} \end{bmatrix}
$$
Then it's log would be:

In [35]:
m = np.matrix([[3/8, 3/8], [3/8, 5/8]])
idt = np.matrix([[1, 0], [0, 1]])
log_m = numpy.matrix([[0.0, 0.0], [0.0, 0.0]])
for i in range(1, 50):
    log_m += ((-1)**(i+1)) * (((m - idt)**i )/i)
print(log_m)

[[-1.52242413  1.01757553]
 [ 1.01757553 -0.84404045]]


In [44]:
import scipy as sc
import scipy.linalg as scli
print('von neumann entropy is: ', -np.trace((m * log_m) / np.log(2)))


von neumann entropy is:  0.48366738206361204
